In [1]:
import pandas as pd

In [10]:
preventiva = pd.read_csv("cd-etapa (3)_Dados completos_data - 2025-10-17T075817.370 (2).csv", sep='\t', encoding='latin-1')

In [11]:
preventiva

     CD_Resp transportador (grupo)          Cidade Cliente  pedido_gemco
0       1100             DOMICILIO  SANTA BARBARA DE GOIAS    1101636148
1       1100             DOMICILIO                 GOIANIA    1096258498
2       1100             DOMICILIO                 GOIANIA    1103381975
3       1100             DOMICILIO                 GOIANIA    1103380688
4       1100             DOMICILIO    APARECIDA DE GOIANIA    1103278675
..       ...                   ...                     ...           ...
136     1100             DOMICILIO                ANAPOLIS    1103384339
137     1100             DOMICILIO                 GOIANIA    1103389496
138     1100             DOMICILIO                 GOIANIA    1103393818
139     1100             DOMICILIO                 GOIANIA    1103571413
140     1100             DOMICILIO                ANAPOLIS    1103521520

[141 rows x 4 columns]

In [8]:
filtrado = preventiva.query(" `Cidade Cliente` != 'ITUMBIARA' ")

In [12]:
filtrado

     CD_Resp transportador (grupo)          Cidade Cliente  pedido_gemco
0       1100             DOMICILIO  SANTA BARBARA DE GOIAS    1101636148
1       1100             DOMICILIO                 GOIANIA    1096258498
2       1100             DOMICILIO                 GOIANIA    1103381975
3       1100             DOMICILIO                 GOIANIA    1103380688
4       1100             DOMICILIO    APARECIDA DE GOIANIA    1103278675
..       ...                   ...                     ...           ...
136     1100             DOMICILIO                ANAPOLIS    1103384339
137     1100             DOMICILIO                 GOIANIA    1103389496
138     1100             DOMICILIO                 GOIANIA    1103393818
139     1100             DOMICILIO                 GOIANIA    1103571413
140     1100             DOMICILIO                ANAPOLIS    1103521520

[139 rows x 4 columns]

In [3]:
preventiva_df = pd.read_excel('Relatorio_DOMICILIO_2025-10-31 (2).xlsx')

In [5]:
preventiva_df.columns

Index(['transportador (grupo)', 'Cidade Cliente', 'PEDIDO 1P/FULL'], dtype='object')

In [6]:
preventiva_df[['PEDIDO 1P/FULL']]

     PEDIDO 1P/FULL
0        1106390363
1        1106339530
2        1106463782
3        1106473559
4        1106378135
..              ...
128      1106444652
129      1106272027
130      1106276180
131      1106287686
132      1106115549

[133 rows x 1 columns]